twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site:
            title: "Elao_"
            description: "Elao est un atelier de co-conception d'applications web et mobile sur mesure."
            birthdate: 04/01/2005
            contact:
                email: contact@elao.com
                phone: +33 (0)4 82 53 37 19

            menu:
                - { path: 'services', label: 'Nos services' }
                - { path: 'methodology', label: 'Méthodologie' }
                - { path: 'case_studies', label: 'Études de cas' }
                - { path: 'values', label: 'Nos valeurs' }
                - { path: 'team', label: 'La tribu' }
                - { path: 'blog', label: 'Blog' }
                - { path: 'contact', label: 'Contact', icon: 'contact', mobileClass: 'nav-mobile__item--large' }
            footer:
                - { path: 'services', label: 'Nos services' }
                - { path: 'team', label: 'La tribu' }
                - { path: 'methodology', label: 'Méthodologie' }
                - { path: 'blog', label: 'Blog' }
                - { path: 'case_studies', label: 'Études de cas' }
                - { path: 'contact', label: 'Contact' }
                - { path: 'values', label: 'Nos valeurs' }
