twig:
    strict_variables: true
    default_path: '%kernel.project_dir%/templates'
    globals:
        site:
            title: "Elao_"
            description: "Elao est un atelier de co-conception d'applications web et mobile sur mesure."
            birthdate: 04/01/2005
            contact:
                email: contact@elao.com
                phone: 04 82 53 37 19

            menu:
                - { path: 'services', label: 'Services' }
                - { path: 'methodology', label: 'Méthodologie' }
                - { path: 'case_studies', label: 'Études de cas' }
                - { path: 'values', label: 'Valeurs' }
                - { path: 'team', label: 'La tribu' }
                - { path: 'blog', label: 'Blog' }
                - { path: 'contact', label: 'Contact', icon: 'contact', mobileClass: 'nav-mobile__item--large' }
            footer:
                -
                    - { path: 'services', label: 'Services' }
                    - { path: 'methodology', label: 'Méthodologie' }
                    - { path: 'case_studies', label: 'Études de cas' }
                -
                    - { path: 'values', label: 'Valeurs' }
                    - { path: 'team', label: 'La tribu' }
                    - { path: 'blog', label: 'Blog' }
                -
                    - { path: 'contact', label: 'Contact' }

            home:
                highlights:
                    caseStudy: tribu
