services:
    App\Bridge\Glide\Bundle\GlideUrlBuilder:
        arguments:
            - '@router'
            - ~ # $route set by the extension
            - ~ # $signKey set by the extension

    App\Bridge\Glide\Bundle\Twig\GlideExtension:
        arguments:
            - '@League\Glide\Server'
            - '@App\Bridge\Glide\Bundle\GlideUrlBuilder'
            - ~ # $presetsNames set by the extension
            - ~ # $preGenerate set by the extension
            - '@logger'
        tags:
            - { name: twig.extension }

    League\Glide\Responses\SymfonyResponseFactory: ~

    League\Glide\Server:
        factory: [League\Glide\ServerFactory, create]
        arguments:
            - ~ # $config set by the extension

    App\Bridge\Glide\Bundle\Controller\ResizeImageController:
        public: true
        arguments:
            - '@League\Glide\Server'
            - # $signKey set by the extension
