#index:
#    path: /
#    controller: App\Controller\DefaultController::index

twitter:
    schemes: https
    host: twitter.com
    resource: routes/external/twitter.yaml
    options:
        stenope:
            ignore: true
